import Head from "next/head";
import { RiMoonFoggyFill } from "react-icons/ri";
import { GiClover } from "react-icons/gi";

import Image from "next/image";

import Timeline from "../components/timeline";
import Project from "../components/project";

import tonyaji from "../public/tony.png";

import web1 from "../public/sertiv/msib.jpg";
import web2 from "../public/sertiv/react.png";
import web3 from "../public/sertiv/javascript.png";
import web4 from "../public/sertiv/cakap.jpg";
import web5 from "../public/sertiv/git.png";
import web6 from "../public/sertiv/htmlcss.png";
import web7 from "../public/sertiv/xml.jpg";

import gundar from "../public/logogundar.png";
import prisma from "../public/prisma.png";

import ijs from "../public/iconjavascript.svg";
import reactjs from "../public/icons/reactjs.svg";
import nextjs from "../public/icons/next-js.svg";
import tailwind from "../public/icons/tailwind-css.svg";
import adobexd from "../public/icons/adobe-xd.svg";
import chakraui from "../public/icons/chakra-ui.svg";
import reacticons from "../public/icons/reacticons.svg";

import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Next Portofolio aji</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-800">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between ">
            <h1 className="text-xl text-gray-700 font-burtons hover:-rotate-7  cursor-pointer dark:text-white">
              welcome to my portofolio
            </h1>
            <ul className="flex items-center ">
              <li>
                <a
                  className=" font-silkscreen bg-gradient-to-r from-cyan-500 to-sky-500 hover:from-teal-500 hover:to-cyan-500 text-white px-4 py-2 rounded mr-5"
                  href="https://drive.google.com/file/d/1pLf1l7aqjoOJ1V3uvF8_NlLGaC2bSDdj/view"
                >
                  My Resume
                </a>
              </li>
              <li>
                <RiMoonFoggyFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-3xl text-gray-700 dark:text-white "
                />
              </li>
            </ul>
          </nav>
          <div className=" text-center px-10 py-2 ">
            <div className="relative w-full max-w-7xl dark:bg-none">
              <div class="absolute top-0 -left-4 w-72 h-72 bg-purple-300 rounded-full mix-blend-multiply filter blur-xl opacity-70 animate-blob"></div>
              <div class="absolute top-0 -right-4 w-72 h-72 bg-cyan-300 rounded-full mix-blend-multiply filter blur-xl opacity-70 animate-blob animation-delay-2000"></div>
              <div class="absolute -bottom-8 left-20 w-72 h-72 bg-pink-300 rounded-full mix-blend-multiply filter blur-xl opacity-70 animate-blob animation-delay-4000"></div>
              {/* gambargua */}
              <div className="transition ease-in-out delay-50 hover:-translate-y-3 hover:scale-110 duration-200 relative mx-auto bg-gradient-to-b from-cyan-600 to-sky-600 dark:bg-gradient-to-b dark:from-teal-500 dark:to-sky-600 rounded-full w-32 h-48 overflow-hidden ">
                <Image src={tonyaji} layout="fill" objectFit="cover" />
              </div>

              <h2 className=" text-teal-600 dark:text-teal-200 pt-5 text-2xl font-silkscreen font-semibold">
                Tony Aji Palguno
              </h2>
              <h3 className="font-burtons text-lg text-slate-400 pb-3">
                FrontEnd Engineer
              </h3>
              <p className="text-md py-5 leading-8 text-gray-800 max-w-2xl mx-auto dark:text-white">
                "Freshgraduate Teknik Informatika Universitas Gunadarma dengan
                ketertarikan sebagai Programmer terlebih dalam{" "}
                <strong>FrontEnd Web Developer</strong> dan pengembangan
                aplikasi lainnya. Menyukai dan sedang mempelajari framework
                JavaScript seperti <strong>NextJS</strong> dengan library{" "}
                <strong>ReactJS</strong> dengan framework CSS yang sering
                digunakan yaitu <strong>Tailwind.</strong> dan juga saat ini
                saya sedang mempelajari hal baru seperti MongoDB dan ExpressJS.”
              </p>
            </div>
            {/* icons */}
            <div class="flex justify-center gap-24 py-5 ">
              <a
                class="hover:-translate-y-2 transition ease-in-out delay-75  text-blue-500 hover:text-blue-500/75 dark:text-white dark:hover:text-sky-300"
                href="https://www.linkedin.com/in/tony-aji-palguno-2302b71b5/"
                target="_blank"
                rel="noreferrer"
                aria-label="LinkedIn"
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  class="h-12 w-11"
                  fill="currentColor"
                  viewBox="0 0 24 24"
                  aria-hidden="true"
                >
                  <path d="M12 0c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm-2 16h-2v-6h2v6zm-1-6.891c-.607 0-1.1-.496-1.1-1.109 0-.612.492-1.109 1.1-1.109s1.1.497 1.1 1.109c0 .613-.493 1.109-1.1 1.109zm8 6.891h-1.998v-2.861c0-1.881-2.002-1.722-2.002 0v2.861h-2v-6h2v1.093c.872-1.616 4-1.736 4 1.548v3.359z" />
                </svg>
              </a>

              <a
                class="hover:-translate-y-2 transition ease-in-out delay-75 text-gray-900 hover:text-gray-900/75 dark:text-white dark:hover:text-blue-200"
                href="https://github.com/tonyaji19"
                target="_blank"
                rel="noreferrer"
                aria-label="GitHub"
              >
                <svg
                  class="h-12 w-12"
                  fill="currentColor"
                  viewBox="0 0 24 24"
                  aria-hidden="true"
                >
                  <path
                    fill-rule="evenodd"
                    d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z"
                    clip-rule="evenodd"
                  ></path>
                </svg>
              </a>

              <a
                class="hover:-translate-y-2 transition ease-in-out delay-75 text-pink-600 hover:text-pink-600/75 dark:text-white dark:hover:text-pink-600"
                href="/dribbble"
                target="_blank"
                rel="noreferrer"
                aria-label="Dribbble"
              >
                <svg
                  class="h-12 w-12"
                  fill="currentColor"
                  viewBox="0 0 24 24"
                  aria-hidden="true"
                >
                  <path
                    fill-rule="evenodd"
                    d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10c5.51 0 10-4.48 10-10S17.51 2 12 2zm6.605 4.61a8.502 8.502 0 011.93 5.314c-.281-.054-3.101-.629-5.943-.271-.065-.141-.12-.293-.184-.445a25.416 25.416 0 00-.564-1.236c3.145-1.28 4.577-3.124 4.761-3.362zM12 3.475c2.17 0 4.154.813 5.662 2.148-.152.216-1.443 1.941-4.48 3.08-1.399-2.57-2.95-4.675-3.189-5A8.687 8.687 0 0112 3.475zm-3.633.803a53.896 53.896 0 013.167 4.935c-3.992 1.063-7.517 1.04-7.896 1.04a8.581 8.581 0 014.729-5.975zM3.453 12.01v-.26c.37.01 4.512.065 8.775-1.215.25.477.477.965.694 1.453-.109.033-.228.065-.336.098-4.404 1.42-6.747 5.303-6.942 5.629a8.522 8.522 0 01-2.19-5.705zM12 20.547a8.482 8.482 0 01-5.239-1.8c.152-.315 1.888-3.656 6.703-5.337.022-.01.033-.01.054-.022a35.318 35.318 0 011.823 6.475 8.4 8.4 0 01-3.341.684zm4.761-1.465c-.086-.52-.542-3.015-1.659-6.084 2.679-.423 5.022.271 5.314.369a8.468 8.468 0 01-3.655 5.715z"
                    clip-rule="evenodd"
                  ></path>
                </svg>
              </a>
            </div>
          </div>

          {/* section new */}
          <div>
            <h3 className="text-2xl font-silkscreen font-semibold text-center text-gray-700 pt-8  dark:text-white">
              Education
            </h3>
            <div className=" grid grid-cols-2 gap-4 cursor-pointer">
              <a href="" className="cursor-pointer">
                <div className=" bg-gradient-to-r from-indigo-300 to-purple-400 hover:-translate-y-2 hover:transition duration-500 ease-out text-white text-left px-8 py-5 rounded-xl my-10 dark:bg-white">
                  <div className="flex space-x-4 xl:space-x-8 ">
                    <Image src={gundar} width={50} height={50}></Image>

                    <div>
                      <h3 className="text-lg font-medium sm:text-sm xs:text-xs">
                        Universitas Gunadarma
                      </h3>
                      <h4 className="font-roboto sm:text-xs xs:text-xs">
                        Teknik Informatika{" "}
                        <span className="text-xs pl-1">2018-2022</span>
                      </h4>
                    </div>
                  </div>
                </div>
              </a>

              <a href="" className="cursor-pointer">
                <div className="bg-gradient-to-r from-blue-400 to-emerald-400 hover:-translate-y-2 hover:transition duration-500 ease-out text-white text-left px-8 py-5 rounded-xl my-10 dark:bg-white">
                  <div className="flex space-x-4 xl:space-x-8 ">
                    <Image src={prisma} width={50} height={50}></Image>

                    <div>
                      <h3 className="text-lg font-medium sm:text-sm xs:text-xs">
                        SMA Prisma Sanjaya
                      </h3>
                      <h4 className="font-roboto sm:text-xs xs:text-xs">
                        IPA <span className="text-xs pl-1">2015-2018</span>
                      </h4>
                    </div>
                  </div>
                </div>
              </a>
            </div>
          </div>
        </section>

        {/* //timeline */}
        <div className="p-10">
          <Timeline />
        </div>

        {/* project */}
        <Project />

        {/* TOOLS */}
        <section>
          <div>
            <h3 className="text-2xl font-silkscreen font-semibold text-gray-700 pt-20 pb-14 text-center dark:text-white">
              Tools
            </h3>
          </div>

          <div className="grid grid-cols-3 gap-4 p-auto m-auto lg:px-60  text-black">
            <div className="bgc text-center  shadow-xl  p-2 rounded-2xl ">
              <Image src={ijs} width={60} height={60} />
              <h3 className="text-lg text-xs font-medium py-1">JavaScript</h3>
            </div>

            <div className="bgc text-center shadow-xl  p-2 rounded-2xl ">
              <Image src={reactjs} width={60} height={60} />
              <h3 className="text-lg text-xs font-medium pt-2 pb-2">
                React JS
              </h3>
            </div>

            <div className="bgc text-center shadow-xl  p-2 rounded-2xl ">
              <Image src={reacticons} width={60} height={60} />
              <h3 className="text-lg text-xs font-medium pt-2 pb-2">
                React Icons
              </h3>
            </div>

            <div className="bgc text-center shadow-xl  p-2 rounded-2xl dark:bg-slate-300">
              <Image src={tailwind} width={60} height={60} />
              <h3 className="text-lg text-xs font-medium pt-2 pb-2">
                Tailwind
              </h3>
            </div>

            <div className="bgc text-center shadow-xl p-2 rounded-2xl dark:bg-slate-300">
              <Image src={chakraui} width={60} height={60} />
              <h3 className="text-lg text-xs font-medium pt-2 pb-2">
                Chakra UI
              </h3>
            </div>

            <div className="bgc text-center shadow-xl p-2 rounded-2xl dark:bg-slate-300">
              <Image src={nextjs} width={60} height={60} />
              <h3 className="text-lg text-xs font-medium pt-2 pb-2">Next JS</h3>
            </div>
            <div className="bgc text-center shadow-xl p-2 rounded-2xl dark:bg-slate-300">
              <Image src={adobexd} width={60} height={60} />
              <h3 className="text-lg text-xs font-medium pt-2 pb-2">Next JS</h3>
            </div>
          </div>
        </section>

        <section className="dark:text-white">
          <div>
            <h3
              id="sertiv"
              className="scroll-smooth text-2xl font-silkscreen font-semibold text-gray-700 text-center  pt-16 dark:text-white"
            >
              Certification
            </h3>
          </div>

          <div className="flex flex-col gap-10 py-5 lg:flex-row lg:flex-wrap">
            <div className="basis-1/4 flex-1">
              <Image
                src={web1}
                className="rounded-lg object-contain transition ease-in-out  hover:-translate-y-3 hover:scale-150 duration-200"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/4 flex-1">
              <Image
                src={web2}
                className="rounded-lg object-contain transition ease-in-out  hover:-translate-y-3 hover:scale-150 duration-200"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/4 flex-1">
              <Image
                src={web3}
                className="rounded-lg object-contain transition ease-in-out  hover:-translate-y-3 hover:scale-150 duration-200"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/4 flex-1">
              <Image
                src={web4}
                className="rounded-lg object-contain transition ease-in-out  hover:-translate-y-3 hover:scale-150 duration-200"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/4 flex-1">
              <Image
                src={web5}
                className="rounded-lg object-contain transition ease-in-out  hover:-translate-y-3 hover:scale-150 duration-200"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/4 flex-1">
              <Image
                src={web6}
                className="rounded-lg object-contain transition ease-in-out  hover:-translate-y-3 hover:scale-150 duration-200"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/4 flex-4">
              <Image
                src={web7}
                className="rounded-lg object-contain transition ease-in-out  hover:-translate-y-3 hover:scale-150 duration-200"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
          </div>
        </section>

        <footer class=" text-center">
          <div class="mx-auto max-w-screen-xl px-10 pb-6 sm:w-full lg:w-full ">
            <div class="mx-auto max-w-5xl space-y-4  ">
              <nav class="rounded-3xl border-4 border-gray-800 dark:border-teal-900 p-6 bg-gradient-to-r from-cyan-500 to-sky-500 hover:from-teal-500 hover:to-cyan-500  ">
                <ul class="flex flex-wrap justify-center gap-6 text-sm font-bold ">
                  <li>
                    <a
                      class="text-gray-900 transition hover:text-gray-900/75 dark:hover:text-white"
                      href="/"
                      target="_blank"
                      rel="noreferrer"
                    >
                      Website
                    </a>
                  </li>

                  <li>
                    <a
                      class="text-gray-900 transition hover:text-gray-900/75 dark:hover:text-white"
                      href="/"
                      target="_blank"
                      rel="noreferrer"
                    >
                      Project
                    </a>
                  </li>

                  <li>
                    <a
                      class="text-gray-900 transition hover:text-gray-900/75 dark:hover:text-white"
                      href="/"
                      target="_blank"
                      rel="noreferrer"
                    >
                      Blog
                    </a>
                  </li>

                  <li>
                    <a
                      class="text-gray-900 transition hover:text-gray-900/75 dark:hover:text-white"
                      href="/"
                      target="_blank"
                      rel="noreferrer"
                    >
                      Portfolio
                    </a>
                  </li>
                </ul>
              </nav>

              <span class="mt-4 block text-xs text-gray-500 dark:text-gray-400 dark:hover:text-white">
                &copy; Made with 🖤 by Tony
              </span>
            </div>
          </div>
        </footer>
      </main>
    </div>
  );
}
